package com.writer.recognition

import android.content.Context
import android.util.Log
import java.io.DataInputStream
import java.io.BufferedInputStream

/**
 * Next-word predictor backed by a pre-compiled bigram frequency table.
 *
 * Binary format (big-endian, generated by `./gradlew compileBigrams`):
 * - Header: [vocab_size: UInt16] [bigram_count: UInt32]
 * - Vocab: [length: UInt8] [utf8 bytes] × vocab_size
 * - Bigrams: [w1_id: UInt16] [w2_id: UInt16] [count: UInt32] × bigram_count
 *   Sorted by (w1_id asc, count desc) for binary search.
 *
 * Source corpus: Google Web Trillion Word Corpus via Norvig (MIT license).
 */
class BigramPredictor private constructor(
    private val wordToId: Map<String, Int>,
    private val idToWord: Array<String>,
    /** Flat array: [w1_id, w2_id, count, w1_id, w2_id, count, ...] */
    private val bigrams: IntArray,
    private val bigramCount: Int
) {
    companion object {
        private const val TAG = "BigramPredictor"
        private const val ASSET_NAME = "bigrams.bin"

        /** Load the bigram table from assets. Returns null if the asset is missing. */
        fun load(context: Context): BigramPredictor? {
            return try {
                val t0 = System.nanoTime()
                val input = DataInputStream(BufferedInputStream(context.assets.open(ASSET_NAME)))
                val predictor = input.use { read(it) }
                val ms = (System.nanoTime() - t0) / 1_000_000
                Log.d(TAG, "Loaded $ASSET_NAME: ${predictor.idToWord.size} words, ${predictor.bigramCount} bigrams in ${ms}ms")
                predictor
            } catch (e: Exception) {
                Log.w(TAG, "Failed to load $ASSET_NAME: ${e.message}")
                null
            }
        }

        private fun read(input: DataInputStream): BigramPredictor {
            val vocabSize = input.readUnsignedShort()
            val bigramCount = input.readInt()

            // Read vocabulary
            val idToWord = Array(vocabSize) { "" }
            val wordToId = HashMap<String, Int>(vocabSize * 2)
            for (i in 0 until vocabSize) {
                val len = input.readUnsignedByte()
                val bytes = ByteArray(len)
                input.readFully(bytes)
                val word = String(bytes, Charsets.UTF_8)
                idToWord[i] = word
                wordToId[word] = i
            }

            // Read bigrams as flat int array: [w1, w2, count, w1, w2, count, ...]
            val bigrams = IntArray(bigramCount * 3)
            for (i in 0 until bigramCount) {
                bigrams[i * 3] = input.readUnsignedShort()
                bigrams[i * 3 + 1] = input.readUnsignedShort()
                bigrams[i * 3 + 2] = input.readInt()
            }

            return BigramPredictor(wordToId, idToWord, bigrams, bigramCount)
        }
    }

    /**
     * Predict the next word(s) given the last written word.
     * Returns up to [maxResults] predictions sorted by frequency.
     */
    fun predict(lastWord: String, maxResults: Int = 3): List<String> {
        val w1Id = wordToId[lastWord.lowercase()] ?: return emptyList()

        // Binary search for first bigram with this w1_id
        var lo = 0
        var hi = bigramCount - 1
        while (lo < hi) {
            val mid = (lo + hi) / 2
            if (bigrams[mid * 3] < w1Id) lo = mid + 1 else hi = mid
        }

        // Collect results (already sorted by count desc within each w1_id)
        val results = mutableListOf<String>()
        var i = lo
        while (i < bigramCount && bigrams[i * 3] == w1Id && results.size < maxResults) {
            val w2Id = bigrams[i * 3 + 1]
            results.add(idToWord[w2Id])
            i++
        }
        return results
    }

    /** Check if a word exists in the vocabulary. */
    fun hasWord(word: String): Boolean = wordToId.containsKey(word.lowercase())
}
